description: returns an array of configuration values

uses: php:file

variables:
  schema:
    type: object

    properties:
      config_name:
          type: string
      config_options:
          type: code

    required:
      - config_name

  form:
    - '*'

definitions:
  file_name: '{{config_name}}' #snake
  file_path: config/
  php_code: |
      {{""}}
      return [
      {% for config in config_options %}
        '{{ config.key }}' => {{ config.value }},
      {% endfor %}
      ];
